spring:
  application:
    name: cp-portal-ui
  main:
    allow-bean-definition-overriding: true
    allow-circular-references: true
  freemarker:
    template-loader-path: classpath:/templates/

server:
  port: ${PORT:8092}
  servlet:
    session:
      cookie:
        name: CPADMINPORTALSESSION

management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: health

logging:
  level:
    ROOT: INFO
  path: classpath:logback-spring.xml
  file: logs/application.log

keycloak:
  oauth:
    info:
      uri: ${KEYCLOAK_URI}/realms/${KEYCLOAK_CP_REALM}/protocol/openid-connect/userinfo
    token:
      check:
        uri: ${KEYCLOAK_URI}/realms/${KEYCLOAK_CP_REALM}/protocol/openid-connect/token/introspect
      access:
        uri: ${KEYCLOAK_URI}/realms/${KEYCLOAK_CP_REALM}/protocol/openid-connect/token
    logout:
      url: ${KEYCLOAK_URI}/realms/${KEYCLOAK_CP_REALM}/protocol/openid-connect/logout
    authorization:
      uri: ${KEYCLOAK_URI}/realms/${KEYCLOAK_CP_REALM}/protocol/openid-connect/auth
    client:
      id: ${KEYCLOAK_CP_CLIENT_ID}
      secret: ${KEYCLOAK_CP_CLIENT_SECRET}
      scope:
      superAdminRole: cp-cluster-admin-role
---
spring:
  config:
    activate:
      on-profile: local

cpApi:
  url: http://localhost:3333

chaosApi:
  url: http://localhost:8092

catalogApi:
  url: http://localhost:8093

---
spring:
  config:
    activate:
      on-profile: prod

cpApi:
  url: ${CP_PORTAL_API_URI}

chaosApi:
  url: ${CP_PORTAL_CHAOS_API_URI}

catalogApi:
  url: ${CP_PORTAL_CATALOG_API_URI}